minimum_reviewers: 1
build_steps:
 - "uptime"
merge: true
delete_branch: true
 - "uptime"
merge: true
delete_branch: true
merge_method: squash
build_steps_R16B03: 
 - "uptime"
 - "erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().'  -noshell"
build_steps_18:
 - "uptime"
 - "env"
 - "erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().'  -noshell"

