minimum_reviewers: 1
build_steps:
 - "uptime"
 - "uptime"
merge: true
delete_branch: true
merge_method: squash
build_steps:
 - "uptime"
 - "uptime"
build_steps_R16B03:
 - "erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().'  -noshell"

build_steps_18:
 - "erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().'  -noshell"

build_steps_19:
 - "erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().'  -noshell"

