minimum_reviewers: 0
before:
 - "sudo apt-get update"
 - "sudo apt-get install apt-transport-https ca-certificates"
build_steps:
 - "uptime"
 - "erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().'  -noshell"
 - "kerl active"
merge: true
otp: R16B03
